-- MySQL Script generated by MySQL Workbench
-- Sat Apr  5 01:26:51 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema airbnb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema airbnb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `airbnb` DEFAULT CHARACTER SET utf8 ;
USE `airbnb` ;

-- -----------------------------------------------------
-- Table `airbnb`.`Guest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbnb`.`Guest` (
  `guestId` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`guestId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`Host`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbnb`.`Host` (
  `hostId` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`hostId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`Cancelation Policy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbnb`.`Cancelation Policy` (
  `cancelationPolicyId` VARCHAR(45) NOT NULL,
  `minDaysBeforeArrival` INT NOT NULL,
  `refundPercentage` DOUBLE NOT NULL,
  PRIMARY KEY (`cancelationPolicyId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`Friend Policy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbnb`.`Friend Policy` (
  `minNumberOfFriends` INT NOT NULL,
  `discountPercentage` DOUBLE NOT NULL,
  `friendPolicyId` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`friendPolicyId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`Property`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbnb`.`Property` (
  `propertyId` VARCHAR(45) NOT NULL,
  `title` VARCHAR(60) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `description` LONGTEXT NULL,
  `pricePerNight` DOUBLE NOT NULL,
  `maxGuests` INT NOT NULL,
  `latitude` DOUBLE NOT NULL,
  `longitude` DOUBLE NOT NULL,
  `check-in instructions` LONGTEXT NULL,
  `Host_hostId` VARCHAR(45) NOT NULL,
  `Cancelation Policy_cancelationPolicyId` VARCHAR(45) NULL,
  `Friend Policy_friendPolicyId` VARCHAR(45) NULL,
  PRIMARY KEY (`propertyId`, `Host_hostId`),
  INDEX `fk_Property_Host1_idx` (`Host_hostId` ASC) VISIBLE,
  INDEX `fk_Property_Cancelation Policy1_idx` (`Cancelation Policy_cancelationPolicyId` ASC) VISIBLE,
  INDEX `fk_Property_Friend Policy1_idx` (`Friend Policy_friendPolicyId` ASC) VISIBLE,
  CONSTRAINT `fk_Property_Host1`
    FOREIGN KEY (`Host_hostId`)
    REFERENCES `airbnb`.`Host` (`hostId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Property_Cancelation Policy1`
    FOREIGN KEY (`Cancelation Policy_cancelationPolicyId`)
    REFERENCES `airbnb`.`Cancelation Policy` (`cancelationPolicyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Property_Friend Policy1`
    FOREIGN KEY (`Friend Policy_friendPolicyId`)
    REFERENCES `airbnb`.`Friend Policy` (`friendPolicyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`Photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbnb`.`Photo` (
  `link` VARCHAR(120) NOT NULL,
  `Property_propertyId` VARCHAR(45) NOT NULL,
  `Property_Host_hostId` VARCHAR(45) NOT NULL,
  `Property_propertyId1` VARCHAR(45) NOT NULL,
  `Property_Host_hostId1` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`link`),
  INDEX `fk_Photo_Property1_idx` (`Property_propertyId` ASC, `Property_Host_hostId` ASC) VISIBLE,
  INDEX `fk_Photo_Property2_idx` (`Property_propertyId1` ASC, `Property_Host_hostId1` ASC) VISIBLE,
  CONSTRAINT `fk_Photo_Property1`
    FOREIGN KEY (`Property_propertyId` , `Property_Host_hostId`)
    REFERENCES `airbnb`.`Property` (`propertyId` , `Host_hostId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Photo_Property2`
    FOREIGN KEY (`Property_propertyId1` , `Property_Host_hostId1`)
    REFERENCES `airbnb`.`Property` (`propertyId` , `Host_hostId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbnb`.`User` (
  `username` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `phone_number` VARCHAR(45) NULL,
  `Guest_guestId` VARCHAR(45) NOT NULL,
  `Photo_link` VARCHAR(120) NULL,
  `Host_hostId` VARCHAR(45) NULL,
  `User_username` VARCHAR(45) NOT NULL,
  `User_Guest_guestId` VARCHAR(45) NOT NULL,
  `User_Host_hostId` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`username`, `Guest_guestId`, `Host_hostId`),
  INDEX `fk_User_Guest1_idx` (`Guest_guestId` ASC) VISIBLE,
  INDEX `fk_User_Photo1_idx` (`Photo_link` ASC) VISIBLE,
  INDEX `fk_User_Host1_idx` (`Host_hostId` ASC) VISIBLE,
  INDEX `fk_User_User1_idx` (`User_username` ASC, `User_Guest_guestId` ASC, `User_Host_hostId` ASC) VISIBLE,
  CONSTRAINT `fk_User_Guest1`
    FOREIGN KEY (`Guest_guestId`)
    REFERENCES `airbnb`.`Guest` (`guestId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Photo1`
    FOREIGN KEY (`Photo_link`)
    REFERENCES `airbnb`.`Photo` (`link`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Host1`
    FOREIGN KEY (`Host_hostId`)
    REFERENCES `airbnb`.`Host` (`hostId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_User1`
    FOREIGN KEY (`User_username` , `User_Guest_guestId` , `User_Host_hostId`)
    REFERENCES `airbnb`.`User` (`username` , `Guest_guestId` , `Host_hostId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`Supporter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbnb`.`Supporter` (
  `supporterId` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`supporterId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`Facility`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbnb`.`Facility` (
  `facilityId` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` LONGTEXT NULL,
  PRIMARY KEY (`facilityId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`Rule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbnb`.`Rule` (
  `ruleId` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` LONGTEXT NOT NULL,
  PRIMARY KEY (`ruleId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`Discount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbnb`.`Discount` (
  `discountId` VARCHAR(45) NOT NULL,
  `startDate` DATE NOT NULL,
  `endDate` DATE NOT NULL,
  `discountPercentage` DOUBLE NOT NULL,
  `minBookingDays` INT NOT NULL DEFAULT 0,
  `Guest_guestId` VARCHAR(45) NOT NULL,
  `Property_propertyId` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`discountId`, `Property_propertyId`, `Guest_guestId`),
  INDEX `fk_Discount_Guest1_idx` (`Guest_guestId` ASC) VISIBLE,
  INDEX `fk_Discount_Property1_idx` (`Property_propertyId` ASC) VISIBLE,
  CONSTRAINT `fk_Discount_Guest1`
    FOREIGN KEY (`Guest_guestId`)
    REFERENCES `airbnb`.`Guest` (`guestId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Discount_Property1`
    FOREIGN KEY (`Property_propertyId`)
    REFERENCES `airbnb`.`Property` (`propertyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`Booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbnb`.`Booking` (
  `bookingId` VARCHAR(45) NOT NULL,
  `numGuests` INT NOT NULL,
  `arrivalDate` DATE NOT NULL,
  `departureDate` DATE NOT NULL,
  `totalCost` DOUBLE NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `Guest_guestId` VARCHAR(45) NOT NULL,
  `Property_propertyId` VARCHAR(45) NOT NULL,
  `Property_Friend Policy_minNumberOfFriends` INT NULL,
  `Property_Friend Policy_discountPercentage` DOUBLE NULL,
  `Property_Cancelation Policy_minDaysBeforeArrival` INT NULL,
  `Property_Cancelation Policy_refundPercentage` DOUBLE NULL,
  PRIMARY KEY (`bookingId`, `Guest_guestId`, `Property_propertyId`),
  INDEX `fk_Booking_Guest1_idx` (`Guest_guestId` ASC) VISIBLE,
  INDEX `fk_Booking_Property1_idx` (`Property_propertyId` ASC, `Property_Friend Policy_minNumberOfFriends` ASC, `Property_Friend Policy_discountPercentage` ASC, `Property_Cancelation Policy_minDaysBeforeArrival` ASC, `Property_Cancelation Policy_refundPercentage` ASC) VISIBLE,
  CONSTRAINT `fk_Booking_Guest1`
    FOREIGN KEY (`Guest_guestId`)
    REFERENCES `airbnb`.`Guest` (`guestId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Booking_Property1`
    FOREIGN KEY (`Property_propertyId`)
    REFERENCES `airbnb`.`Property` (`propertyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`Review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbnb`.`Review` (
  `reviewId` VARCHAR(45) NOT NULL,
  `text` LONGTEXT NULL,
  `stars` INT NOT NULL,
  `Guest_guestId` VARCHAR(45) NOT NULL,
  `Host_hostId` VARCHAR(45) NOT NULL,
  `Guest_guestId1` VARCHAR(45) NOT NULL,
  `Property_propertyId` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`reviewId`, `Guest_guestId`, `Property_propertyId`, `Host_hostId`, `Guest_guestId1`),
  INDEX `fk_Review_Guest1_idx` (`Guest_guestId` ASC) VISIBLE,
  INDEX `fk_Review_Host1_idx` (`Host_hostId` ASC) VISIBLE,
  INDEX `fk_Review_Guest2_idx` (`Guest_guestId1` ASC) VISIBLE,
  INDEX `fk_Review_Property1_idx` (`Property_propertyId` ASC) VISIBLE,
  CONSTRAINT `fk_Review_Guest1`
    FOREIGN KEY (`Guest_guestId`)
    REFERENCES `airbnb`.`Guest` (`guestId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Review_Host1`
    FOREIGN KEY (`Host_hostId`)
    REFERENCES `airbnb`.`Host` (`hostId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Review_Guest2`
    FOREIGN KEY (`Guest_guestId1`)
    REFERENCES `airbnb`.`Guest` (`guestId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Review_Property1`
    FOREIGN KEY (`Property_propertyId`)
    REFERENCES `airbnb`.`Property` (`propertyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`Payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbnb`.`Payment` (
  `paymentId` VARCHAR(45) NOT NULL,
  `method` VARCHAR(45) NOT NULL,
  `amount` DOUBLE NOT NULL,
  `Booking_bookingId` VARCHAR(45) NOT NULL,
  `Guest_guestId` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`paymentId`, `Booking_bookingId`, `Guest_guestId`),
  INDEX `fk_Payment_Booking1_idx` (`Booking_bookingId` ASC) VISIBLE,
  INDEX `fk_Payment_Guest1_idx` (`Guest_guestId` ASC) VISIBLE,
  CONSTRAINT `fk_Payment_Booking1`
    FOREIGN KEY (`Booking_bookingId`)
    REFERENCES `airbnb`.`Booking` (`bookingId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Payment_Guest1`
    FOREIGN KEY (`Guest_guestId`)
    REFERENCES `airbnb`.`Guest` (`guestId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`Message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbnb`.`Message` (
  `messageId` VARCHAR(45) NOT NULL,
  `text` LONGTEXT NOT NULL,
  `date` DATE NOT NULL,
  `User_username` VARCHAR(45) NOT NULL,
  `User_username1` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`messageId`, `User_username1`, `User_username`),
  INDEX `fk_Message_User1_idx` (`User_username` ASC) VISIBLE,
  INDEX `fk_Message_User2_idx` (`User_username1` ASC) VISIBLE,
  CONSTRAINT `fk_Message_User1`
    FOREIGN KEY (`User_username`)
    REFERENCES `airbnb`.`User` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Message_User2`
    FOREIGN KEY (`User_username1`)
    REFERENCES `airbnb`.`User` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`Request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbnb`.`Request` (
  `requestId` VARCHAR(45) NOT NULL,
  `text` LONGTEXT NOT NULL,
  `Guest_guestId` VARCHAR(45) NOT NULL,
  `Property_propertyId` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`requestId`, `Guest_guestId`, `Property_propertyId`),
  INDEX `fk_Request_Guest1_idx` (`Guest_guestId` ASC) VISIBLE,
  INDEX `fk_Request_Property1_idx` (`Property_propertyId` ASC) VISIBLE,
  CONSTRAINT `fk_Request_Guest1`
    FOREIGN KEY (`Guest_guestId`)
    REFERENCES `airbnb`.`Guest` (`guestId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Request_Property1`
    FOREIGN KEY (`Property_propertyId`)
    REFERENCES `airbnb`.`Property` (`propertyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`Friend`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbnb`.`Friend` (
  `friendId` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `Property_propertyId` VARCHAR(45) NOT NULL,
  `Property_Host_hostId` VARCHAR(45) NOT NULL,
  `User_username` VARCHAR(45) NOT NULL,
  `User_Guest_guestId` VARCHAR(45) NOT NULL,
  `User_Host_hostId` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`friendId`, `User_username`, `User_Guest_guestId`, `User_Host_hostId`, `Property_propertyId`, `Property_Host_hostId`),
  INDEX `fk_Friend_Property1_idx` (`Property_propertyId` ASC, `Property_Host_hostId` ASC) VISIBLE,
  INDEX `fk_Friend_User1_idx` (`User_username` ASC, `User_Guest_guestId` ASC, `User_Host_hostId` ASC) VISIBLE,
  CONSTRAINT `fk_Friend_Property1`
    FOREIGN KEY (`Property_propertyId` , `Property_Host_hostId`)
    REFERENCES `airbnb`.`Property` (`propertyId` , `Host_hostId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Friend_User1`
    FOREIGN KEY (`User_username` , `User_Guest_guestId` , `User_Host_hostId`)
    REFERENCES `airbnb`.`User` (`username` , `Guest_guestId` , `Host_hostId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`Reward`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbnb`.`Reward` (
  `rewardId` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` LONGTEXT NULL,
  `User_username` VARCHAR(45) NOT NULL,
  `Host_hostId` VARCHAR(45) NOT NULL,
  `Property_propertyId` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`rewardId`, `Host_hostId`, `User_username`, `Property_propertyId`),
  INDEX `fk_Reward_User1_idx` (`User_username` ASC) VISIBLE,
  INDEX `fk_Reward_Host1_idx` (`Host_hostId` ASC) VISIBLE,
  INDEX `fk_Reward_Property1_idx` (`Property_propertyId` ASC) VISIBLE,
  CONSTRAINT `fk_Reward_User1`
    FOREIGN KEY (`User_username`)
    REFERENCES `airbnb`.`User` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reward_Host1`
    FOREIGN KEY (`Host_hostId`)
    REFERENCES `airbnb`.`Host` (`hostId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reward_Property1`
    FOREIGN KEY (`Property_propertyId`)
    REFERENCES `airbnb`.`Property` (`propertyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`Time Period`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbnb`.`Time Period` (
  `startDate` DATE NOT NULL,
  `endDate` DATE NOT NULL,
  PRIMARY KEY (`startDate`, `endDate`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`manages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbnb`.`manages` (
  `Property_propertyId` VARCHAR(45) NOT NULL,
  `Supporter_supporterId` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NULL,
  PRIMARY KEY (`Property_propertyId`, `Supporter_supporterId`),
  INDEX `fk_Property_has_Supporter_Supporter1_idx` (`Supporter_supporterId` ASC) VISIBLE,
  INDEX `fk_Property_has_Supporter_Property1_idx` (`Property_propertyId` ASC) VISIBLE,
  CONSTRAINT `fk_Property_has_Supporter_Property1`
    FOREIGN KEY (`Property_propertyId`)
    REFERENCES `airbnb`.`Property` (`propertyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Property_has_Supporter_Supporter1`
    FOREIGN KEY (`Supporter_supporterId`)
    REFERENCES `airbnb`.`Supporter` (`supporterId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`has`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbnb`.`has` (
  `Property_propertyId` VARCHAR(45) NOT NULL,
  `Nearby Attraction_latitude` DOUBLE NOT NULL,
  `Nearby Attraction_longitude` DOUBLE NOT NULL,
  INDEX `fk_Property_has_Nearby Attraction_Nearby Attraction1_idx` (`Nearby Attraction_latitude` ASC, `Nearby Attraction_longitude` ASC) VISIBLE,
  INDEX `fk_Property_has_Nearby Attraction_Property1_idx` (`Property_propertyId` ASC) VISIBLE,
  CONSTRAINT `fk_Property_has_Nearby Attraction_Property1`
    FOREIGN KEY (`Property_propertyId`)
    REFERENCES `airbnb`.`Property` (`propertyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Property_has_Nearby Attraction_Nearby Attraction1`
    FOREIGN KEY (`Nearby Attraction_latitude` , `Nearby Attraction_longitude`)
    REFERENCES `airbnb`.`Nearby Attraction` (`latitude` , `longitude`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`is represented by`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbnb`.`is represented by` (
  `User_username` VARCHAR(45) NOT NULL,
  `Host_hostId` VARCHAR(45) NOT NULL,
  INDEX `fk_User_has_Host_Host1_idx` (`Host_hostId` ASC) VISIBLE,
  INDEX `fk_User_has_Host_User1_idx` (`User_username` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Host_User1`
    FOREIGN KEY (`User_username`)
    REFERENCES `airbnb`.`User` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Host_Host1`
    FOREIGN KEY (`Host_hostId`)
    REFERENCES `airbnb`.`Host` (`hostId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`is in wish list of`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbnb`.`is in wish list of` (
  `Property_propertyId` VARCHAR(45) NOT NULL,
  `User_username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Property_propertyId`, `User_username`),
  INDEX `fk_Property_has_User_User1_idx` (`User_username` ASC) VISIBLE,
  INDEX `fk_Property_has_User_Property1_idx` (`Property_propertyId` ASC) VISIBLE,
  CONSTRAINT `fk_Property_has_User_Property1`
    FOREIGN KEY (`Property_propertyId`)
    REFERENCES `airbnb`.`Property` (`propertyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Property_has_User_User1`
    FOREIGN KEY (`User_username`)
    REFERENCES `airbnb`.`User` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`is in favorites list of`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbnb`.`is in favorites list of` (
  `Property_propertyId` VARCHAR(45) NOT NULL,
  `User_username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Property_propertyId`, `User_username`),
  INDEX `fk_Property_has_User_User2_idx` (`User_username` ASC) VISIBLE,
  INDEX `fk_Property_has_User_Property2_idx` (`Property_propertyId` ASC) VISIBLE,
  CONSTRAINT `fk_Property_has_User_Property2`
    FOREIGN KEY (`Property_propertyId`)
    REFERENCES `airbnb`.`Property` (`propertyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Property_has_User_User2`
    FOREIGN KEY (`User_username`)
    REFERENCES `airbnb`.`User` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbnb`.`Employee` (
  `employeeId` VARCHAR(45) NOT NULL,
  `salary` DOUBLE NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`employeeId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`works at`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbnb`.`works at` (
  `Employee_employeeId` VARCHAR(45) NOT NULL,
  `Property_propertyId` VARCHAR(45) NOT NULL,
  `Property_Host_hostId` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Employee_employeeId`, `Property_propertyId`, `Property_Host_hostId`),
  INDEX `fk_Employee_has_Property_Property1_idx` (`Property_propertyId` ASC, `Property_Host_hostId` ASC) VISIBLE,
  INDEX `fk_Employee_has_Property_Employee1_idx` (`Employee_employeeId` ASC) VISIBLE,
  CONSTRAINT `fk_Employee_has_Property_Employee1`
    FOREIGN KEY (`Employee_employeeId`)
    REFERENCES `airbnb`.`Employee` (`employeeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employee_has_Property_Property1`
    FOREIGN KEY (`Property_propertyId` , `Property_Host_hostId`)
    REFERENCES `airbnb`.`Property` (`propertyId` , `Host_hostId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`has matching rate with`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbnb`.`has matching rate with` (
  `User_username` VARCHAR(45) NOT NULL,
  `Property_propertyId` VARCHAR(45) NOT NULL,
  `Property_Host_hostId` VARCHAR(45) NOT NULL,
  `matching rate` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`User_username`, `Property_propertyId`, `Property_Host_hostId`),
  INDEX `fk_User_has_Property_Property1_idx` (`Property_propertyId` ASC, `Property_Host_hostId` ASC) VISIBLE,
  INDEX `fk_User_has_Property_User1_idx` (`User_username` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Property_User1`
    FOREIGN KEY (`User_username`)
    REFERENCES `airbnb`.`User` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Property_Property1`
    FOREIGN KEY (`Property_propertyId` , `Property_Host_hostId`)
    REFERENCES `airbnb`.`Property` (`propertyId` , `Host_hostId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`Nearby Attraction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbnb`.`Nearby Attraction` (
  `title` VARCHAR(45) NOT NULL,
  `description` LONGTEXT NULL,
  `longitude` DOUBLE NOT NULL,
  `latitude` DOUBLE NOT NULL,
  PRIMARY KEY (`latitude`, `longitude`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`has`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbnb`.`has` (
  `Property_propertyId` VARCHAR(45) NOT NULL,
  `Nearby Attraction_latitude` DOUBLE NOT NULL,
  `Nearby Attraction_longitude` DOUBLE NOT NULL,
  INDEX `fk_Property_has_Nearby Attraction_Nearby Attraction1_idx` (`Nearby Attraction_latitude` ASC, `Nearby Attraction_longitude` ASC) VISIBLE,
  INDEX `fk_Property_has_Nearby Attraction_Property1_idx` (`Property_propertyId` ASC) VISIBLE,
  CONSTRAINT `fk_Property_has_Nearby Attraction_Property1`
    FOREIGN KEY (`Property_propertyId`)
    REFERENCES `airbnb`.`Property` (`propertyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Property_has_Nearby Attraction_Nearby Attraction1`
    FOREIGN KEY (`Nearby Attraction_latitude` , `Nearby Attraction_longitude`)
    REFERENCES `airbnb`.`Nearby Attraction` (`latitude` , `longitude`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`Advertisement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbnb`.`Advertisement` (
  `advertisementId` VARCHAR(45) NOT NULL,
  `clicks` INT NOT NULL,
  `cost` DOUBLE NOT NULL,
  `Property_propertyId` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`advertisementId`, `Property_propertyId`),
  INDEX `fk_Advertisement_Property1_idx` (`Property_propertyId` ASC) VISIBLE,
  CONSTRAINT `fk_Advertisement_Property1`
    FOREIGN KEY (`Property_propertyId`)
    REFERENCES `airbnb`.`Property` (`propertyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`is applied in`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbnb`.`is applied in` (
  `Rule_ruleId` VARCHAR(45) NOT NULL,
  `Property_propertyId` VARCHAR(45) NOT NULL,
  `Property_Host_hostId` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Rule_ruleId`, `Property_propertyId`, `Property_Host_hostId`),
  INDEX `fk_Rule_has_Property_Property1_idx` (`Property_propertyId` ASC, `Property_Host_hostId` ASC) VISIBLE,
  INDEX `fk_Rule_has_Property_Rule1_idx` (`Rule_ruleId` ASC) VISIBLE,
  CONSTRAINT `fk_Rule_has_Property_Rule1`
    FOREIGN KEY (`Rule_ruleId`)
    REFERENCES `airbnb`.`Rule` (`ruleId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rule_has_Property_Property1`
    FOREIGN KEY (`Property_propertyId` , `Property_Host_hostId`)
    REFERENCES `airbnb`.`Property` (`propertyId` , `Host_hostId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`is availiable during`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbnb`.`is availiable during` (
  `Property_propertyId` VARCHAR(45) NOT NULL,
  `Time Period_startDate` DATE NOT NULL,
  `Time Period_endDate` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Property_propertyId`, `Time Period_startDate`, `Time Period_endDate`),
  INDEX `fk_Property_has_Time Period_Time Period1_idx` (`Time Period_startDate` ASC, `Time Period_endDate` ASC) VISIBLE,
  INDEX `fk_Property_has_Time Period_Property1_idx` (`Property_propertyId` ASC) VISIBLE,
  CONSTRAINT `fk_Property_has_Time Period_Property1`
    FOREIGN KEY (`Property_propertyId`)
    REFERENCES `airbnb`.`Property` (`propertyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Property_has_Time Period_Time Period1`
    FOREIGN KEY (`Time Period_startDate` , `Time Period_endDate`)
    REFERENCES `airbnb`.`Time Period` (`startDate` , `endDate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
